// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package database

import (
	"context"
)

const getGroupIDByGroupName = `-- name: GetGroupIDByGroupName :one
SELECT id FROM groups WHERE group_name = $1
`

func (q *Queries) GetGroupIDByGroupName(ctx context.Context, groupName string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getGroupIDByGroupName, groupName)
	var id int32
	err := row.Scan(&id)
	return id, err
}
