// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Group struct {
	ID        int32
	GroupName string
}

type Song struct {
	ID          int32
	SongName    string
	ReleaseDate sql.NullTime
	Text        sql.NullString
	Link        sql.NullString
	GroupID     int32
}
